name: Azkaban
safe: true
lsi: false
pygments: true

tagline: "Open-source Workflow Manager"
image: "img/app.png"
repo: "azkaban/azkaban"

plugins_repo: "azkaban/azkaban-plugins"
docs: "/"
home: "http://azkaban.github.io"
